### PR TITLE
Prepend record type to prefix

### PR DESCRIPTION
**Pull request by eyvind**
**Description**

The default name for a txt record in the new registry format is `<record type>-<domain name>`. This can prevent creating the registry txt record for a zone apex, since there is no guarantee that `<record type>-<domain name>` is accessible to external-dns.

This is similar to #449, where a txt prefix not ending in `.` caused the same problem.

When a prefix is provided without a record type, the new txt registry format creates a txt record of the form `<txt prefix><record type>-<domain name>`. This breaks existing external-dns deployments creating zone apex records where the txt prefix does not contain a record type template.

Change the implementation so that if there is no record type template in either of the affixes, the record type is prepended to the prefix instead of to the domain name: `<record type>-<txt prefix><domain name>`.

Related to #2971

**Checklist**

- [x] Unit tests updated
- [ ] End user documentation updated

### CODE REVIEW

**Comment by psalaberria002** [comment]
I am very skeptical of running our own fork with a potential fix that may never me accepted upstream. Can we get the discussion with the maintainers going before merging this?

**Comment by finnag** [comment]
I think the idea was to send this upstream?

**Comment by psalaberria002** [comment]
> I think the idea was to send this upstream?

Perfect.

**Comment by ngerstle-cognite** [comment]
Does external DNS track which format it's using for a domain somewhere, or does it look for any of the formats it creates?
I think this would work for us, but might be messy to merge upstream, if it means adding yet another txt record name to look for.

**Comment by eyvind** [comment]
It only looks in one configurable place, sort of. For the record type prefix feature, it creates both prefixed and unprefixed variants and looks for both.

**Comment by eyvind** [comment]
Giving up on this in favour of manually migrating prefixes.

**Pull request closed without merging**
